apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/redis-sentinel.yaml
  - resources/redis.pdb.yaml

patches:
  - path: patches/redis-node.statefulset.yaml
images:
  - name: docker.io/bitnami/redis-sentinel
    newName: openanalytics/redis-sentinel
  - name: docker.io/bitnami/redis
    newName: openanalytics/redis
